CANVAS_WIDTH = 600
CANVAS_HEIGHT = 600
CANVAS_PADDING = 10

BULLET_WIDTH = 10
BULLET_HEIGHT = 10

PLAYER_COLOR = "yellow"
CANVAS_COLOR = "black"
ASTEROID_COLOR = "red"
BULLET_COLOR = "white"

PLAYER_WIDTH = 60
PLAYER_HEIGHT = 40

MIN_WIDTH_ASTEROID = 30
MAX_WIDTH_ASTEROID = 70
MIN_HEIGHT_ASTEROID = 20
MAX_HEIGHT_ASTEROID = 60
MIN_SPEED_ASTEROID = 2
MAX_SPEED_ASTEROID = 10

TIMEOUT_ASTEROID_MC = 1000
TIMEOUT_SHOOT_MC = 200