CANVAS_WIDTH = 800
CANVAS_HEIGTH = 600

PLAYER_SIZE = 50
PLAYER_START_X = CANVAS_WIDTH // 2
PLAYER_START_Y = CANVAS_HEIGTH // 2
PLAYER_START_ANGLE = 0

PLAYER_START_SPEED = 0
PLAYER_MIN_SPEED = 0
PLAYER_MAX_SPEED = 10
PLAYER_UP_SPEED = 0.5
PLAYER_DOWN_SPEED = 0.25

ASTEROID_MIN_SIZE = 50
ASTEROID_MAX_SIZE = 100
ASTEROID_MIN_X = 0
ASTEROID_MAX_X = CANVAS_WIDTH
ASTEROID_MIN_Y = 0
ASTEROID_MAX_Y = CANVAS_HEIGTH
ASTEROID_MIN_ANGLE = 0
ASTEROID_MAX_ANGLE = 360
ASTEROID_MIN_SPEED = 1
ASTEROID_MAX_SPEED = 5

DISTANCE_BEETWEN_PLAYER_ASTEROID = 200

BULLET_SIZE = 10
BULLET_SPEED = 15

BULLET_MAX_DISTANCE = 400
