CIRCLE_RADIUS = 200
CIRCLE_CENTER_X = 300
CIRCLE_CONTER_Y = 300
CIRCLE_COLOR = "black"

POINT_START_POSITION = 0
POINT_SPEED = 1
POINT_RADIUS = 20
POINT_COLOR = "red"

CANVAS_HEIGHT = 600
CANVAS_WIDTH = 600
CANVAS_COLOR = "white"
