#!/bin/bash

MONITOR_SERVERS_TIME="5"
DEFAULT_NET="192.168.100.0/24"

NEED_COLLECT_CPU_INFO="yes"
NEED_COLLECT_RAM_INFO="yes"
NEED_COLLECT_ACTIVE_CONNECTIONS_INFO="yes"
NEED_COLLECT_ACTIVE_PROCESSES_INFO="yes"
NEED_COLLECT_VERSION_OS_INFO="yes"

CPU_MAX_TEMPERATURE="90"
LOW_DISK_SPACE="10"
